### ISSUE TITLE
关于上传的疑问

### ISSUE THREAD

**Issue by pigcan** [imMMX/ubnt-erx-shadowsocks-libev#1]
> 交叉编译的方式是在 Ubuntu 上进行

现在编译好的文件应该是在  `ubnt-erx-shadowsocks-libev/shadowsocks-libev/bin` 这个下面吗?

上传到路由器指的是不是通过 scp 上传到 `/usr/bin` 目录下 ? 与此同时应该还需要一份 ss 运行起来的 config 文件吧，存在 `/etc/shadowsocks-libev/config.json` 吗？

运行是不是就是把 `/usr/bin/ss-server` 写到启动项然后每次重启自动运行？

**Comment by imMMX** [comment]
1. 可执行文件应该在你当前目录的 erx 文件夹里的 bin 中。
2. 嗯，可以用 scp 上传。config.json 文件可以自己编辑一份，也可以直接带参数用命令行启动不用 -c 指定 config.json。我目前还未把 config.json 的样例文件打包进去。
3. erx 使用的应当是 ss-redir 做透明代理。

**Comment by pigcan** [comment]
@imMMX  感谢回复

我使用的是你的方案二 直接通过 `sh build_ss.sh` 来进行交叉编译。

我看了下 shell 脚本 里面并没有相关输出到  erx 的逻辑， docker 方案会有。

**Comment by imMMX** [comment]
嗯，脚本中会编译到 --prefix=$ss_path/shadowsocks-libev 目录，$ss_path 为当前文件夹，即 ubnt-erx-shadowsocks-libev/shadowsocks-libev/bin 中。

感谢提醒，将在脚本中添加打包至 erx 的逻辑。
