### ISSUE TITLE
寻求帮助关于dns污染

### ISSUE THREAD

**Issue by xingezhang** [imMMX/ubnt-erx-shadowsocks-libev#2]
您好，我用您的这个脚本完成了ss的交叉编译，非常感谢您的付出，不知道您是否有时间帮忙再写一个脚本，交叉编译https-dns-proxy？
项目在这https://github.com/aarond10/https_dns_proxy
我想用这个来解决dns污染的问题，谢谢啦

**Comment by xlighting2017** [comment]
这东西不是首先要先能够解析 dns.google.com ?

**Comment by xingezhang** [comment]
我也不是很懂，不知道这个是不是可以透过ss去访问dns.google.com?我原来用过dnscrypt-proxy，现在也没法用了，好像tcp也被污染了？

**Comment by xingezhang** [comment]
刚才Google了一下，确实不能用，详细见https://www.v2ex.com/t/366503
