### ISSUE TITLE
可以用在ubnt-er -l3上吗？

### ISSUE THREAD

**Issue by JunShine** [imMMX/ubnt-erx-shadowsocks-libev#3]
是不是把脚本里的mipsel改成mips64就可以了，我这个不会交叉编译命令的新手看到命令好晕了......

**Comment by imMMX** [comment]
erl3 好像有 2GB 空间，不可以直接编译吗？

**Comment by JunShine** [comment]
erl3确实可以直接编译哈，可更换的内置U盘空间还可以更大。不过直接编译我怕会影响到正在运行的网络，而且直接部署编译环境也不好。所以想做交叉编译哈。这个问题已解决哈关闭了哈~~~
